name: "Setup Node"

description: "Setup Node"

inputs:
  node-version:
    description: "Node version"
    required: true
    default: 18.10.0
  npm-version:
    description: "NPM version (if not defined, the default one from node-version will be used)"
    required: true
    default: 8.19.2

runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: "${{ inputs.node-version }}"
    - name: Setup npm
      shell: bash
      run: |
        npm install -g npm@${{ inputs.npm-version }}
    - name: Installed versions
      shell: bash
      run: |
        echo "Node version:"
        node -v
        echo "Npm version:"
        which npm
        npm -v
