name: "Setup NPM for Raycast"

description: "Setup NPM for Raycast"

runs:
  using: "composite"
  steps:
    - name: Setup npm
      shell: bash
      run: |
        npm install npm@8.19.2 --location=global
        echo "Npm path: $(which npm)"
        echo "Npm version: $(npm -v)"
